name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
      ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml torch

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files_yaml: |
            cfg:
              - 'cfg/**.yaml'

    - name: Start tmate session
      uses: mxschmitt/action-tmate@v3
      env:
          CFG_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.cfg_all_changed_files }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.number }}

    - name: Wait for user input
      run: |
        echo "Tmate session is running. Connect to it using the SSH command provided in the logs."
        echo "Press [CTRL+C] to exit the session."
        while true; do sleep 60; done

      - name: Validate YAML
        if: steps.changed-files-yaml.outputs.cfg_any_changed == 'true'
        env:
          CFG_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.cfg_all_changed_files }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/validate_yaml.py
